---
name: Test - Validate function of the action

"on":
  pull_request:
    branches:
      - "master"
    paths:
      - 'action.yml'
      - 'main.js'

permissions:
  contents: read

jobs:
  TestUnit-Testcase01:
    name: TestUnit-Case01
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Find Tag
        id: tagger
        uses: ./
        with:
          include: 'v*'
          exclude: '*-rc*'
          commit-ish: 'HEAD~'
          skip-unshallow: 'true'

      - name: Find RC Tag
        id: rcs
        uses: ./
        with:
          include: '*-rc*'
          skip-unshallow: 'true'

      - name: Show Tag
        id: display
        run: |
          echo 'Output from Find Tag: ${{steps.tagger.outputs.tag}}'
          echo 'Output from Find RC Tag: ${{steps.rcs.outputs.tag}}'


  TestUnit-Testcase02:
    name: TestUnit-Case02
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Find Tag (commit-ish example)
        id: tagger
        uses: ./
        with:
          include: 'v*'
          exclude: '*-rc*'
          # Suppose you want to query a tag closes to a commit no later than 20 hours ago (excluding any commits in the last 20 hours)
          # Don't ask me why you'd want to do this, it's just demonstrating commit-ish usage.
          commit-ish: '@{ 20 hours ago }'

      - name: Find RC Tag
        id: rcs
        uses: ./
        with:
          include: '*-rc*'
          # We must skip unshallow here as git fetch will fail on subsequent attempts
          skip-unshallow: 'true'

      - name: Show Tag
        id: display
        run: |
          echo 'Output from Find Tag (commit-ish example): ${{steps.tagger.outputs.tag}}'
          echo 'Output from Find RC Tag: ${{steps.rcs.outputs.tag}}'


  TestUnit-Testcase03:
    name: TestUnit-Case03
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Find specific Tag (commit-ish HEAD)
        id: tagger
        uses: ./
        with:
          include: 'v2.3'
          exact-match: 'false'
          no-tags-text: 'false'
          commit-ish: 'HEAD'

      - name: Find not existing Tag (commit-ish HEAD)
        id: net
        uses: ./
        with:
          include: 'v100.3'
          exact-match: 'false'
          no-tags-text: 'false'
          commit-ish: 'HEAD'

      - name: Show Tag
        id: display
        run: |
          echo 'Output from Find specific Tag (commit-ish HEAD): ${{steps.tagger.outputs.tag}}'
          echo 'Output from FFind not existing Tag (commit-ish HEAD): ${{steps.net.outputs.tag}}'
